name: tensor-safe
version: 0.1.0.0
github: "leopiney/tensor-safe"
license: BSD3
author: Leonardo Pineyro
maintainer: leopiney@gmail.com
copyright: 2019 Leonardo Pineyro
synopsis: Create valid deep neural network architectures
description: TensorSafe provides a very simple API to create deep neural networks structures which are validated using Dependent Types. Given a list of Layers and an initial Shape, TensorSafe is able to check and corroborate the structure of the network. Also, it's possible to extract the definition and compile it to a target language like Python and JavaScript.
category: AI, Dependent Types, Language, Library, Program

extra-source-files:
  - README.md

ghc-options: -Wall -freduction-depth=0

dependencies:
  - base >= 4.7 && < 5
  - casing >= 0.1.4.0 && < 0.1.5
  - cmdargs >= 0.10.20 && < 0.11
  - containers >= 0.6.0.1 && < 0.7
  - extra >= 1.6 && < 1.7
  - formatting >= 6.3.6 && < 6.4
  - ghc-typelits-extra >= 0.3 && < 0.4
  - hint >= 0.9.0 && < 1.0
  - singletons >= 2.5.1 && < 2.6
  - text >= 1.2.3.1 && < 1.3
  - vector >= 0.12 && < 0.13
  - vector-sized > 1.2 && < 1.3

library:
  source-dirs: src

executables:
  tensor-safe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tensor-safe
