name: tensor-safe
version: 0.1.0.0
github: "leopiney/tensor-safe"
license: BSD3
author: "Leonardo Pineyro"
maintainer: "leopiney@gmail.com"
copyright: "2019 Leonardo Pineyro"

extra-source-files:
  - README.md

ghc-options: -Wall -freduction-depth=0

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.0.1 && < 0.7
  - extra >= 1.6 && < 1.7
  - formatting >= 6.3.6 && < 6.4
  - ghc-typelits-extra >= 0.3 && < 0.4
  - singletons >= 2.5.1 && < 2.6
  - text >= 1.2.3.1 && < 1.3
  - vector >= 0.12 && < 0.13
  - vector-sized > 1.2 && < 1.3

library:
  source-dirs: src

executables:
  tensor-safe-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tensor-safe

tests:
  tensor-safe-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tensor-safe
